# Generated by Django 5.1.2 on 2024-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('profile', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
